---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecom-db-credentials
  namespace: ecom-dev
spec:
  encryptedData:
    connectionString: AgAcyoW2UJfHVbqv00WRVIIDkFholkUolsVjGcclOGsOlQDQdS+RGqmteWZzAXBkoCnSE3nLdh/xcr3efhbP3iqYCkCX5yPf41V/F7/AayE92CL3LGkPBNlooEuh2jAkIrAErCtrHuyZHfDpvwCp1Ph/ikz9axBLZhrwsJE5Pl6VsWBHV2fT6uKxyCfB1NfCYkKTTE20e7nWb1i0sEZfaNu7/C6lLpAgt0Lo+1CPqFtKHfurbx7/asl1tH8g6oXzZwdnPNg91akHFV67+ZMyzBSOjxHqxouFAJs4IoaSx5sZA5yigO6SMdiFLwARUOKF2W4KXLmMAN3HfGNsfF0kJSsnDdCEgHRXj8nHR2NOpAzCcSFpD9RoXLjzaMLcpegTxIzA+YbAGN0eql6VElCBJDWghdDY0cm+2ezxyHRdfHbAGVo9zzgovtDNkYLtoRGVMqariYJP8UEHD8G04+9MQxeDokZAUgsVY2pzsh4avJbTDSzve6tjtUi84uVhz7Cnvq8+dsCovGxSdARxenu+Mv51nkpyaYIPhLmPuyl70LU+vTaRS6qJfLG10FEBoFtCxb+YupMcJKGznJFh0E8+P8w2oqFkDUE4fA/VGXOzkNED3tKVHwqtie1aByT/AeSyRdOtfvJ8myBxGGnq2GFfVc06/0uVnZAosowMmmSNyiTKUf8u59EBCKz1SlxeOPyUBVGepKpFjQa0V7PNnq8MZLojvb2pFsbMycrSV8DT6Ss/cYDbnwmQiOUpuSg+46f+0uTahyLSGfbnUXuutdtqxqTZm3CqwDXs17+L/Sm3wSwJ/zutly5hicbRd1S8USi+fk+AAbxffZMXO2JKWmRJ4Zx9p3zlUsggceLwSa52nELef/mvFtgsRIBJhHA4/5tynXxnNKb+hSaVB718M6UfM9DmyQIeR8o=
  template:
    metadata:
      name: ecom-db-credentials
      namespace: ecom-dev
