 
-- Table: [account]
SET IDENTITY_INSERT [dbo].[account] ON;
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000000, 'nrpro_1@webroot.com', '0a4286531d649e6e79fa00565b6b85ef0304d6651ac111a277b4b60ef2522ea8', 'hint', 1, 1, NULL, '2009-10-22 14:23:47.203', 'eComWebP', '2011-11-11 00:00:00.000', 'nrpro_1@webroot.com', 1, 1, '2015-06-03 15:40:35.843');
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000001, 'isprod@webroot.com', '331ac40b168a388fff903229eb2cd4c3d8d98b9c0fc2fc26546440498f32f48a', 'testx2', 1, 1, NULL, '2009-10-22 14:35:46.980', 'eComWebP', '2012-01-05 00:00:00.000', 'isprod@webroot.com', 1, 1, '2015-06-03 15:40:35.843');
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000002, 'ecom22@webroot.com', '44d3e5bb3d083d365565559151c6565f86b9e13938282fc632137d58ba68838d', 'test', 1, 1, NULL, '2009-10-22 14:45:31.607', 'eComWebP', '2009-10-22 14:51:16.690', 'eComWebP', 1, 1, '2015-06-03 15:40:35.843');
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000003, 'ecom33@webroot.com', '451f9d2064f54c02911fd509fa807734022e3bcf766c3ee8adf4b2ae35251be1', 'test', 1, 1, NULL, '2009-10-22 14:51:09.253', 'eComWebP', '2009-10-22 14:51:45.840', 'eComWebP', 1, 1, '2015-06-03 15:40:35.843');
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000004, 'naveenghegde@gmail.com', '2496edad581f367e8ca0e4f37ac0514f810c35dcd9059b1004fd808699f1cd91', 'test', 1, 1, NULL, '2009-10-23 00:16:04.257', 'eComWebP', '2013-04-03 00:00:00.000', 'naveenghegde@gmail.c', 1, 1, '2015-06-03 15:40:35.843');
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000005, 'jaketest1@test1.com', 'b0d1193799a1e9efa52dfd291f715a5eec3cbf765b8d52fe5e7625a11bbae164', 'webroot', 1, 1, NULL, '2009-10-23 10:27:05.323', 'eComWebP', '2009-10-23 10:27:25.420', 'eComWebP', 1, 1, '2015-06-03 15:40:35.843');
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000006, 'ecomtest12@webroot.com', 'af4acead17783229f0ee2179ef9aa82f1e0a2d17a8bdfca7048f0ca73dba7cff', 'test', 1, 1, NULL, '2009-10-23 10:39:58.217', 'eComWebP', '2009-10-23 10:40:07.557', 'eComWebP', 1, 1, '2015-06-03 15:40:35.843');
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000007, 'naveenhegde@webroot.com', '662b0b5d0fa6b13cba7e071f6c603076713133f85db0f63261977009238a2539', 'test', 1, 1, NULL, '2009-10-26 10:48:17.400', 'eComWebP', '2009-10-26 10:48:31.860', 'eComWebP', 1, 1, '2015-06-03 15:40:35.843');
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000008, 'nrpro_4@webroot.com', '61b7ff9606edaefe2e486b5226cf78313c4381dac32292f005fa7689386f31d8', 'hint', 1, 1, NULL, '2009-10-26 10:48:20.463', 'eComWebP', '2009-10-26 10:48:44.693', 'eComWebP', 1, 1, '2015-06-03 15:40:35.843');
INSERT INTO [dbo].[account] ([account_id], [account_user_name], [account_password], [password_hint], [account_type_id], [account_status_id], [parent_account_id], [insert_date], [insert_by], [modified_date], [modified_by], [WARN_opt_in], [email_opt_in], [password_reset_date]) VALUES (1000009, 'pm_wisc0@webroot.com', '6922b7560c58fcff5a4c135de0ac27b58243aabd184b20b0b78b1db596586a53', 'password', 1, 1, NULL, '2009-10-26 11:23:32.253', 'eComWebP', '2009-10-26 11:29:04.530', 'eComWebP', 1, 1, '2015-06-03 15:40:35.843');
SET IDENTITY_INSERT [dbo].[account] OFF;
 
-- Table: [cart_json]
SET IDENTITY_INSERT [dbo].[cart_json] ON;
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (1, '{"quantity":"","cart_discount_key":"","routing_action":"","pricing_level":"","message_campaign_id":"92","message_campaign_platform":"ui","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":""}', NULL, 23094323);
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (2, '{"quantity":"","cart_discount_key":"","routing_action":"","pricing_level":"","message_campaign_id":"112","message_campaign_platform":"tray","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":"","p_rc":"1","trx_rc":"1","p_ac":null,"trx_ac":null,"p_rsc":null,"trx_rsc":null,"p_utm_source":null,"trx_utm_source":null,"p_utm_term":null,"trx_utm_term":null,"p_utm_medium":null,"trx_utm_medium":null,"p_utm_content":null,"trx_utm_content":null,"p_utm_campaign":null,"trx_utm_campaign":null,"p_utm_sc":null,"trx_utm_sc":null}', NULL, 23094324);
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (3, '{"quantity":"","cart_discount_key":"FBD4913B-5874-4EA9-81A0-5245A4C8E39E","routing_action":"billing","pricing_level":"","message_campaign_id":"","message_campaign_platform":"","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":""}', 8061596, 23094325);
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (4, '{"quantity":"","cart_discount_key":"","routing_action":"","pricing_level":"","message_campaign_id":"","message_campaign_platform":"","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":""}', NULL, 23094326);
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (9, '{"quantity":"","cart_discount_key":"","routing_action":"","pricing_level":"","message_campaign_id":"93","message_campaign_platform":"ui","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":""}', NULL, 23094330);
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (10, '{"quantity":"","cart_discount_key":"","routing_action":"","pricing_level":"","message_campaign_id":"93","message_campaign_platform":"ui","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":""}', NULL, 23094332);
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (13, '{"quantity":"","cart_discount_key":"","routing_action":"","pricing_level":"","message_campaign_id":"","message_campaign_platform":"","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":""}', NULL, 23094335);
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (15, '{"quantity":"","cart_discount_key":"","routing_action":"","pricing_level":"","message_campaign_id":"94","message_campaign_platform":"modal","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":"","p_rc":"1","trx_rc":"1","p_ac":null,"trx_ac":null,"p_rsc":null,"trx_rsc":null,"p_utm_source":null,"trx_utm_source":null,"p_utm_term":null,"trx_utm_term":null,"p_utm_medium":null,"trx_utm_medium":null,"p_utm_content":null,"trx_utm_content":null,"p_utm_campaign":null,"trx_utm_campaign":null,"p_utm_sc":null,"trx_utm_sc":null}', NULL, 23094337);
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (17, '{"quantity":"","cart_discount_key":"","routing_action":"","pricing_level":"","message_campaign_id":"93","message_campaign_platform":"ui","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":""}', NULL, 23094339);
INSERT INTO [dbo].[cart_json] ([cart_json_id], [cart_json], [cart_order_id], [cart_order_in_process_id]) VALUES (18, '{"quantity":"","cart_discount_key":"","routing_action":"","pricing_level":"","message_campaign_id":"","message_campaign_platform":"","restriction":"","partner_key":"","account_user_name":"","license_attribute_license_value":""}', 8061600, 23094340);
SET IDENTITY_INSERT [dbo].[cart_json] OFF;
 
-- Table: [cart_order]
SET IDENTITY_INSERT [dbo].[cart_order] ON;
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (1, 1, 1, 'E000017950509', 'EMAILREGISTRATION', 'EMAILREGISTRATION', 'WRCART', '1', NULL, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 69964585, '2009-05-28 23:37:51.000', '2009-05-28 23:37:51.000', 'en_US', NULL, NULL, '2009-05-28 23:37:51.780', 'trialRegistration', '2009-05-28 23:37:51.780', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (2, 2, 2, 'E000017950522', 'EMAILREGISTRATION', 'EMAILREGISTRATION', 'WRCART', '1', NULL, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 69964585, '2009-05-28 23:39:25.000', '2009-05-28 23:39:25.000', 'en_US', NULL, NULL, '2009-05-28 23:39:25.923', 'trialRegistration', '2009-05-28 23:39:25.923', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (3, 3, 3, 'E000017950558', 'EMAILREGISTRATION', 'EMAILREGISTRATION', 'WRCART', '1', NULL, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 64532047, '2009-05-28 23:43:58.000', '2009-05-28 23:43:58.000', 'en_US', NULL, NULL, '2009-05-28 23:43:58.310', 'trialRegistration', '2009-05-28 23:43:58.310', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (4, 4, 4, 'E000017950582', 'EMAILREGISTRATION', 'EMAILREGISTRATION', 'WRCART', '1', NULL, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 64532047, '2009-05-28 23:47:00.000', '2009-05-28 23:47:00.000', 'en_US', NULL, NULL, '2009-05-28 23:47:00.287', 'trialRegistration', '2009-05-28 23:47:00.287', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (5, 5, 5, 'E000017950645', 'EMAILREGISTRATION', 'EMAILREGISTRATION', 'WRCART', '1', NULL, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 64532047, '2009-05-28 23:58:16.000', '2009-05-28 23:58:16.000', 'en_US', NULL, NULL, '2009-05-28 23:58:16.507', 'trialRegistration', '2009-05-28 23:58:16.507', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (6, 6, 6, 'E000017950651', 'MSN', 'MSN', 'WRCART', '1673', NULL, '26613', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 0, '2009-05-28 23:59:55.000', '2009-05-28 23:59:55.000', 'en_US', NULL, NULL, '2009-05-28 23:59:55.700', 'MSN', '2009-05-28 23:59:55.700', 'MSN', 2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (7, 7, 7, 'E000017950691', 'EMAILREGISTRATION', 'EMAILREGISTRATION', 'WRCART', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 70922242, '2009-05-29 00:07:52.000', '2009-05-29 00:07:52.000', 'en_US', NULL, NULL, '2009-05-29 00:07:52.843', 'trialRegistration', '2009-05-29 00:07:52.843', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (8, 8, 8, 'E000017950693', 'EMAILREGISTRATION', 'EMAILREGISTRATION', 'WRCART', '1', NULL, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 70922074, '2009-05-29 00:07:56.000', '2009-05-29 00:07:56.000', 'en_US', NULL, NULL, '2009-05-29 00:07:56.923', 'trialRegistration', '2009-05-29 00:07:56.923', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (9, 9, 9, 'E000017950719', 'EMAILREGISTRATION', 'EMAILREGISTRATION', 'WRCART', '1', NULL, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 70276219, '2009-05-29 00:10:39.000', '2009-05-29 00:10:39.000', 'en_US', NULL, NULL, '2009-05-29 00:10:39.290', 'trialRegistration', '2009-05-29 00:10:39.290', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order] ([cart_order_id], [cart_customer_id], [invoice_in_process_id], [vendor_order_code], [order_type], [site_id], [site_url], [p_rc], [p_rsc], [p_ac], [trx_rc], [trx_rsc], [trx_ac], [aid], [pid], [sid], [offer_id], [offer_amount], [total_amount], [sub_total_amount], [tax_amount], [payment_method], [exchange_rate], [session_id], [submission_date], [sales_order_date], [locale], [subject], [comment], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [currency_id], [customer_profile_token], [cart_order_in_process_id], [user_ip], [restriction]) VALUES (10, 10, 10, 'E000017950740', 'MSN', 'MSN', 'WRCART', '1673', NULL, '26613', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, 0.00, 0.00, '0', 1.00, 0, '2009-05-29 00:14:59.000', '2009-05-29 00:14:59.000', 'en_US', NULL, NULL, '2009-05-29 00:14:59.660', 'MSN', '2009-05-29 00:14:59.660', 'MSN', 2, NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [dbo].[cart_order] OFF;
 
-- Table: [cart_order_item]
SET IDENTITY_INSERT [dbo].[cart_order_item] ON;
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (1, 1, 1, 1, 0, 67001, 1, NULL, 0.00, 0.00, 0.00, 0.00, 0, 67001, 67001, 'En_US', '2009-05-28 23:37:51.780', 'trialRegistration', '2009-05-28 23:37:51.780', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (2, 2, 2, 1, 0, 67001, 1, NULL, 0.00, 0.00, 0.00, 0.00, 0, 67001, 67001, 'En_US', '2009-05-28 23:39:25.940', 'trialRegistration', '2009-05-28 23:39:25.940', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (3, 3, 3, 1, 0, 67001, 1, NULL, 0.00, 0.00, 0.00, 0.00, 0, 67001, 67001, 'En_US', '2009-05-28 23:43:58.310', 'trialRegistration', '2009-05-28 23:43:58.310', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (4, 4, 4, 1, 0, 67001, 1, NULL, 0.00, 0.00, 0.00, 0.00, 0, 67001, 67001, 'En_US', '2009-05-28 23:47:00.287', 'trialRegistration', '2009-05-28 23:47:00.287', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (5, 5, 5, 1, 0, 67001, 1, NULL, 0.00, 0.00, 0.00, 0.00, 0, 67001, 67001, 'En_US', '2009-05-28 23:58:16.507', 'trialRegistration', '2009-05-28 23:58:16.507', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (6, 6, 6, 1, 0, 64150, 1, NULL, 39.93, 39.93, 0.00, 0.00, 0, 64150, 64150, 'En_US', '2009-05-28 23:59:55.700', 'MSN', '2009-05-28 23:59:55.700', 'MSN', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (7, 7, 7, 1, 0, 67006, 1, NULL, 0.00, 0.00, 0.00, 0.00, 0, 67006, 67006, 'En_US', '2009-05-29 00:07:52.843', 'trialRegistration', '2009-05-29 00:07:52.843', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (8, 8, 8, 1, 0, 67001, 1, NULL, 0.00, 0.00, 0.00, 0.00, 0, 67001, 67001, 'En_US', '2009-05-29 00:07:56.923', 'trialRegistration', '2009-05-29 00:07:56.923', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (9, 9, 9, 1, 0, 67001, 1, NULL, 0.00, 0.00, 0.00, 0.00, 0, 67001, 67001, 'En_US', '2009-05-29 00:10:39.290', 'trialRegistration', '2009-05-29 00:10:39.290', 'trialRegistration', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[cart_order_item] ([cart_order_item_id], [cart_order_id], [invoice_item_in_process_id], [vendor_id], [line_item], [vendor_product_id], [quantity], [order_item_offer_code], [order_item_offer_amount], [list_price], [unit_price], [tax_item_total], [tax_exempt], [product_id], [conversion_product_id], [product_locale], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id], [cart_order_item_in_process_id], [cart_item_bundle_id], [start_date], [expiration_date], [vendor_order_item_code], [order_item_update_type_id], [license_attribute_license_value], [item_hierarchy_id], [cart_discount_id], [cart_discount_method_id], [discount], [unit_price_pre_vat], [usage_price], [opportunity_line_item_id], [sap_material_number], [storage_gb]) VALUES (10, 10, 10, 1, 0, 64150, 1, NULL, 39.93, 39.93, 0.00, 0.00, 0, 64150, 64150, 'En_US', '2009-05-29 00:14:59.677', 'MSN', '2009-05-29 00:14:59.677', 'MSN', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [dbo].[cart_order_item] OFF;
 
-- Table: [cart_order_item_json]
SET IDENTITY_INSERT [dbo].[cart_order_item_json] ON;
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (1, 37834719, '{}', '2020-08-20 10:05:49.157', '2020-08-20 10:05:49.157');
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (2, 37834718, '{}', '2020-08-20 10:05:49.157', '2020-08-20 10:05:49.157');
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (3, 37834720, '{}', '2020-08-20 10:05:52.237', '2020-08-20 10:05:52.237');
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (4, 37834721, '{}', '2020-08-20 10:05:52.237', '2020-08-20 10:05:52.237');
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (5, 37834722, '{}', '2020-08-20 10:06:03.017', '2020-08-20 10:06:03.017');
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (6, 37834723, '{}', '2020-08-20 10:06:03.017', '2020-08-20 10:06:03.017');
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (7, 37834724, '{}', '2020-08-20 10:06:04.750', '2020-08-20 10:06:04.750');
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (8, 37834725, '{}', '2020-08-20 10:06:04.750', '2020-08-20 10:06:04.750');
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (9, 37834726, '{}', '2020-08-20 10:06:04.750', '2020-08-20 10:06:04.750');
INSERT INTO [dbo].[cart_order_item_json] ([cart_order_item_json_id], [cart_order_item_id], [cart_order_item_json], [insert_date], [modified_date]) VALUES (10, 37834727, '{}', '2020-08-20 10:06:04.750', '2020-08-20 10:06:04.750');
SET IDENTITY_INSERT [dbo].[cart_order_item_json] OFF;
 
-- Table: [cart_order_item_license]
SET IDENTITY_INSERT [dbo].[cart_order_item_license] ON;
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (1, 1, 'SSGBONLNAADIJXHMRDUS', '2009-05-28 23:37:51.810', 'trialRegistration', '2009-05-28 23:37:51.810', 'trialRegistration', 2);
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (2, 2, 'SSGBONLNAADIJXHMYQKR', '2009-05-28 23:39:25.957', 'trialRegistration', '2009-05-28 23:39:25.957', 'trialRegistration', 2);
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (3, 3, 'SSGBONLNAADIJXHNMHTA', '2009-05-28 23:43:58.327', 'trialRegistration', '2009-05-28 23:43:58.327', 'trialRegistration', 2);
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (4, 4, 'SSGBONLNAADIJXHNWKXG', '2009-05-28 23:47:00.287', 'trialRegistration', '2009-05-28 23:47:00.287', 'trialRegistration', 2);
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (5, 5, 'SSGBONLNAADIJXHOWQKR', '2009-05-28 23:58:16.507', 'trialRegistration', '2009-05-28 23:58:16.507', 'trialRegistration', 2);
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (6, 6, 'SSGBMSNIAADIJXHOZGYY', '2009-05-28 23:59:55.713', 'MSN', '2009-05-28 23:59:55.713', 'MSN', 2);
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (7, 7, 'SSGBONLNAADIJXHPQOVO', '2009-05-29 00:07:52.860', 'trialRegistration', '2009-05-29 00:07:52.860', 'trialRegistration', 2);
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (8, 8, 'SSGBONLNAADIJXHPRUIZ', '2009-05-29 00:07:56.923', 'trialRegistration', '2009-05-29 00:07:56.923', 'trialRegistration', 2);
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (9, 9, 'SSGBONLNAADIJXHPXBLN', '2009-05-29 00:10:39.290', 'trialRegistration', '2009-05-29 00:10:39.290', 'trialRegistration', 2);
INSERT INTO [dbo].[cart_order_item_license] ([cart_order_item_license_id], [cart_order_item_id], [keycode], [insert_date], [insert_by], [modified_date], [modified_by], [cart_order_status_id]) VALUES (10, 10, 'SSGBMSNIAADIJXHQKNGL', '2009-05-29 00:14:59.677', 'MSN', '2009-05-29 00:14:59.677', 'MSN', 2);
SET IDENTITY_INSERT [dbo].[cart_order_item_license] OFF;
 
-- Table: [cart_order_message]
SET IDENTITY_INSERT [dbo].[cart_order_message] ON;
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (2, 4229870, 'BB8C82C8-F759-41AC-B2AA-6BF5B04F9908', NULL, 462, 1, NULL, NULL);
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (5, 4229935, '1181744F-5414-4EF5-8BFA-334E26B94753', 80165656, NULL, 1, NULL, NULL);
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (7, 4229965, 'AE1D1E8B-FA7C-43E2-B1AB-F15ECDCD6DA3', 80165701, NULL, 1, NULL, NULL);
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (9, 4229986, 'AE1D1E8B-FA7C-43E2-B1AB-F15ECDCD6DA3', 80165701, NULL, 1, NULL, NULL);
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (11, 4230081, 'BB8C82C8-F759-41AC-B2AA-6BF5B04F9908', NULL, 462, 1, NULL, NULL);
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (13, 4230127, 'BB8C82C8-F759-41AC-B2AA-6BF5B04F9908', NULL, 462, 1, NULL, NULL);
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (19, 4230156, 'BB8C82C8-F759-41AC-B2AA-6BF5B04F9908', NULL, 462, 1, NULL, NULL);
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (20, 4230157, 'F3896581-0C4A-4E50-B106-ADBBDCF46E34', NULL, 294, 1, NULL, NULL);
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (21, 4230155, 'BB8C82C8-F759-41AC-B2AA-6BF5B04F9908', NULL, 462, 1, NULL, NULL);
INSERT INTO [dbo].[cart_order_message] ([cart_order_message_id], [cart_order_id], [message_key], [license_id], [cart_discount_id], [status_id], [message_campaign_id], [message_campaign_platform]) VALUES (26, 4230154, 'AD3634C5-8BBB-4CF7-AFC2-ED14F2BEB61A', NULL, 401, 1, NULL, NULL);
SET IDENTITY_INSERT [dbo].[cart_order_message] OFF;
 
-- Table: [cart_order_partner]
SET IDENTITY_INSERT [dbo].[cart_order_partner] ON;
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (2, 4563327, 3291, 1);
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (5, 4563417, 3291, 2);
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (7, 4563437, 3291, 2);
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (9, 4563455, 3291, 2);
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (11, 4563469, 3291, 2);
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (13, 4564061, 3291, 1);
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (15, 4565704, 3291, 2);
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (17, 4565717, 3291, 2);
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (20, 4565719, 3291, 2);
INSERT INTO [dbo].[cart_order_partner] ([cart_order_partner_id], [cart_order_id], [partner_id], [partner_account_id]) VALUES (21, 4568750, 3291, 3);
SET IDENTITY_INSERT [dbo].[cart_order_partner] OFF;
 
-- Table: [cart_order_route]
SET IDENTITY_INSERT [dbo].[cart_order_route] ON;
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (1, 10924971, 'billing', '2018-08-28 15:16:59.150');
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (2, 10924974, 'billing', '2018-08-28 15:17:08.530');
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (3, 10924975, 'billing', '2018-08-28 15:17:19.930');
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (4, 10925010, 'billing', '2018-08-28 15:19:42.983');
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (5, 10925063, 'billing', '2018-08-28 15:22:48.983');
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (6, 10925071, 'billing', '2018-08-28 15:23:16.050');
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (7, 10925077, 'billing', '2018-08-28 15:23:36.527');
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (8, 10925084, 'billing', '2018-08-28 15:24:18.350');
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (9, 10925108, 'billing', '2018-08-28 15:25:31.537');
INSERT INTO [dbo].[cart_order_route] ([cart_order_route_id], [cart_order_id], [routing_action], [insert_date]) VALUES (10, 10925138, 'billing', '2018-08-28 15:27:13.193');
SET IDENTITY_INSERT [dbo].[cart_order_route] OFF;
 
-- Table: [cart_site_id_order_code_prefix]
SET IDENTITY_INSERT [dbo].[cart_site_id_order_code_prefix] ON;
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (1, 'EPICOR', 'SFDC0', 'Legacy');
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (2, 'WRENTERPRISECART', 'ENT00', 'Online Busines Cart');
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (4, 'enterprise', 'ENT00', 'Online Busines Cart');
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (5, 'CSI', 'CS000', 'CSI');
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (6, 'AUTORENEWAL', 'RA000', 'AutoRenwal');
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (7, 'WRCART', 'ECM00', 'Online Consumer Cart');
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (8, 'MSN', 'MSN00', 'MSN');
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (9, 'PURCHASEORDER', 'PUR00', 'Oracle');
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (10, 'RESELLER', 'RSL00', 'Partner Cart');
INSERT INTO [dbo].[cart_site_id_order_code_prefix] ([cart_site_id_order_code_prefix_id], [site_id], [vendor_order_code_prefix], [site_id_description]) VALUES (11, 'PARTNERSERVICE', 'PSV00', 'PSV');
SET IDENTITY_INSERT [dbo].[cart_site_id_order_code_prefix] OFF;
 
-- Table: [currency]
SET IDENTITY_INSERT [dbo].[currency] ON;
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (1, 'USD', 'US dollar', '$', '$', '$', 1, 1, 'en_AU', 1, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', 0);
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (2, 'EUR', 'Euro', '&euro;', '€', 'EUR', 0.789858, 1.15, 'en_GB', 1, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', 0.18);
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (3, 'AUD', 'AU dollar', 'AU $', 'AU $', 'AU $', 0.976658, 1.3, 'en_AU', 1, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', 0);
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (4, 'GBP', 'Pound Sterling', '&pound;', '£', 'GBP', 0.636557, 1.25, 'en_GB', 1, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', 0.2);
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (5, 'JPY', 'Yen', '&yen;', '¥', 'Yen', 120, 1, 'ja_JP', 1, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', 0.05);
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (6, 'AED', 'UAE Dirham', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', NULL);
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (7, 'AMD', 'Armenian Dram', NULL, NULL, NULL, NULL, NULL, NULL, 1, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', NULL);
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (8, 'ANG', 'Guilder', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', NULL);
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (9, 'AOA', 'Kwanza', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', NULL);
INSERT INTO [dbo].[currency] ([currency_id], [currency_code], [currency_description], [symbol_html], [symbol_utf8], [symbol_text], [exchange_rate], [exchange_multiplier], [dr_locale], [active], [last_modified_date], [last_modified_by], [vat_rate]) VALUES (10, 'ARS', 'Argentine Peso', '$', '$', '$', 4.523, 1, 'en_AU', 0, '2013-01-23 21:06:41.633', 'BOULDER\spalanisamy', 0);
SET IDENTITY_INSERT [dbo].[currency] OFF;
 
-- Table: [license_attribute_license_value]
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (0, 1, 'Inactive', 14, 0);
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (1, 1, 'Active', 13, 0);
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (2, 1, 'Back office disable', 14, 0);
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (3, 1, 'CSI disable', 14, 0);
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (4, 1, 'DR Autorenewal', 13, 0);
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (10, 10, 'Sold', 15, 0);
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (11, 10, 'Overage', 17, 1);
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (12, 10, 'Utility', 16, 1);
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (13, 10, 'Perpetual', 21, 1);
INSERT INTO [dbo].[license_attribute_license_value] ([license_attribute_license_value], [license_attribute_id], [license_attribute_license_value_description], [license_module_type_id], [autobilling_enabled]) VALUES (20, 10, 'Annual', 18, 0);
 
-- Table: [license_category]
SET IDENTITY_INSERT [dbo].[license_category] ON;
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (1, 'SS', 'Webroot SecureAnywhere', 1, 1, NULL, NULL, 1, 'Webroot');
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (2, 'WAV', 'Webroot AntiVirus with AntiSpyware', 1, 1, NULL, NULL, 1, 'Webroot');
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (3, 'WISE', 'Webroot Internet Security Essentials', 1, 1, NULL, NULL, 1, 'Webroot');
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (4, 'WISC', 'Webroot Internet Security Complete', 1, 1, NULL, NULL, 1, 'Webroot');
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (10, 'WW', 'Window Washer 64', 4, 1, NULL, NULL, 1, 'Webroot');
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (20, 'PS', 'Professional Services', 18, 1, NULL, NULL, 1, 'Webroot');
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (21, 'PSIS', 'Installation Services', 18, 1, NULL, NULL, 1, 'Webroot');
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (22, 'PSSVR', 'Spyware and Virus Removal', 18, 1, NULL, NULL, 1, 'Webroot');
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (23, 'PSSHC', 'Security Health Check', 18, 1, NULL, NULL, 1, 'Webroot');
INSERT INTO [dbo].[license_category] ([license_category_id], [license_category_name], [license_category_description], [base_capability_id], [devices_per_seat], [min_order_quantity], [max_order_quantity], [status], [license_category_brand]) VALUES (40, 'AF', 'Anchor Free', 0, 1, NULL, NULL, 1, 'Webroot');
SET IDENTITY_INSERT [dbo].[license_category] OFF;
 
-- Table: [license_key]
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (0, '3B90E2BD-AFB3-4AFD-9500-DCC66113E95E', NULL);
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (1, 'E151E1C7-018B-46EF-93A3-2CB7E01805C8', NULL);
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (2, '757E30FD-F996-4AB1-98CD-FE60C74F7CA7', NULL);
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (3, 'EB0DB8E6-58C2-4358-A1E3-F5E969CBCB95', NULL);
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (4, 'E2B28A01-0038-4740-BBAF-0E68ACBEEAB8', NULL);
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (5, '15D91208-D933-498D-9D5A-27FE1A206F54', NULL);
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (6, '4FAAA4D4-DC41-41EB-9FE8-D44A09E3B251', NULL);
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (7, '2D0AF2A1-7EEC-4457-A12D-3CFD2E7BC8A7', NULL);
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (8, '477DD865-C612-49D0-9E1C-F2ED09B454B7', NULL);
INSERT INTO [dbo].[license_key] ([license_id], [license_key], [salesforce_license_id]) VALUES (9, 'F5B72219-203C-4C92-9685-953056B1ED21', NULL);
 
-- Table: [license_keycode_type]
SET IDENTITY_INSERT [dbo].[license_keycode_type] ON;
INSERT INTO [dbo].[license_keycode_type] ([license_keycode_type_id], [license_keycode_type_description], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (0, 'Non-keycoded', '2006-09-04 08:52:23.000', 'BOULDER\esmart', '2006-09-04 08:52:23.000', 'BOULDER\esmart');
INSERT INTO [dbo].[license_keycode_type] ([license_keycode_type_id], [license_keycode_type_description], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (1, 'Single Site', '2006-09-04 08:51:14.390', 'BOULDER\esmart', '2006-09-04 08:51:14.390', 'BOULDER\esmart');
INSERT INTO [dbo].[license_keycode_type] ([license_keycode_type_id], [license_keycode_type_description], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (2, 'Enterprise keycode varchar(36)', '2006-09-04 08:51:30.140', 'BOULDER\esmart', '2006-09-04 08:51:30.140', 'BOULDER\esmart');
INSERT INTO [dbo].[license_keycode_type] ([license_keycode_type_id], [license_keycode_type_description], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (3, 'Multiple Sites', '2014-03-07 11:29:51.187', 'BOULDER\cfaulkner', '2014-03-07 11:29:51.187', 'BOULDER\cfaulkner');
SET IDENTITY_INSERT [dbo].[license_keycode_type] OFF;
 
-- Table: [partner]
SET IDENTITY_INSERT [dbo].[partner] ON;
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (16, 'WeCloud AB', 1, 1, 'E890E59A-B704-4B49-B202-73BD06B1065C', NULL, '0013z00002qeQYyAAM', '1594664', '2022-10-01 14:35:02.267', 'BOULDER\cfaulkner', '005D0000005jbwBIAQ');
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (984, 'Manage Protect', 2, 1, 'B4F0C607-87E6-4363-9612-4D8FE353AD4B', NULL, '0013z00002qeQ2VAAU', '319454', '2022-10-01 14:35:02.267', 'BOULDER\cfaulkner', '005D0000005jbwBIAQ');
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (1029, 'Excel Micro', 1, 1, '336CEE97-ECBC-4567-AAB1-31E27346CF13', NULL, '0013z00002qeL8zAAE', '218334', '2022-10-01 14:35:02.267', 'BOULDER\cfaulkner', '005D0000005jbwBIAQ');
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (2770, 'gateprotect GmbH', 2, 2, '389BF26D-5DEF-4B27-A7CB-8EEE166E5B24', NULL, '0013z00002qeKhWAAU', '2537760', '2022-10-01 14:35:02.267', 'esmart', '005D0000005jbwBIAQ');
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (2815, 'Continuum Managed Services LLC', 3, 1, '4574B6B5-B89C-4E6C-984C-93358D155949', NULL, '0013z00002qeLtxAAE', '000000', '2022-10-01 14:35:02.267', 'BOULDER\spalanisamy', '005D0000005jbwBIAQ');
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (3065, 'SOTI Inc', 5, 2, 'D8B6E39D-C3AA-4F68-ACE1-F69C6AA21E78', NULL, '0013z00002qeRLUAA2', '000000', '2022-10-01 14:35:02.267', 'esmart', '005D0000005jbwBIAQ');
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (3291, 'Webroot', 2, 1, '6E4025F3-487E-4660-86F9-904DEB6BD714', NULL, '0013z00002qelaxAAA', '000000', '2022-10-01 14:35:02.267', 'BOULDER\spalanisamy', '00520000000ic3bAAA');
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (3639, 'SYNNEX Corp.', 1, 1, '0F684522-54E3-4805-A6E7-488FAC09BFD7', NULL, '001D000002Fuvn0IAB', '000000', '2022-10-17 16:55:18.993', 'OPENTEXT\nnaina.adm', '0033z00002rhljyAAA');
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (4067, 'The Infinite Group', 3, 1, 'DD0D6703-0D06-422E-AEAA-AF6E12D8733F', NULL, '0013z00002qeNjVAAU', '2487750', '2022-10-01 14:35:02.267', 'BOULDER\spalanisamy', '005D0000005jbwBIAQ');
INSERT INTO [dbo].[partner] ([partner_id], [partner_name], [partner_type_id], [partner_status_id], [partner_key], [parent_partner_id], [salesforce_id], [oracle_id], [last_modified_date], [last_modified_by], [account_owner_id]) VALUES (4099, 'BlueChip Infotech', 1, 1, 'B742FD8E-FBB1-44BA-B9D0-951888F08A16', NULL, '0013z00002qeKatAAE', '2651751', '2022-10-01 14:35:02.267', 'BOULDER\spalanisamy', '005D0000005jbwBIAQ');
SET IDENTITY_INSERT [dbo].[partner] OFF;
 
-- Table: [partner_account]
SET IDENTITY_INSERT [dbo].[partner_account] ON;
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (2, 3291, 2543942, 'E4F0FDB0-665B-44E5-9123-03C2EF6712F3', 'eComWebP', 0, 2);
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (3, 4099, 2544342, 'CA6B7CD2-70D5-4C25-B871-B914192631AF', 'eComWebP', 0, 1);
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (4, 4357, 2596535, '1F8AE1FA-88C7-4235-9FF7-F2576450D083', 'eComWebP', 0, 1);
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (6, 2770, 2541506, 'D1B13B6B-268F-4935-B2E3-F19AED00E70B', 'eComWebP', 0, 2);
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (7, 3291, 2843495, 'DCE2C9B1-E4D6-47F7-8ACD-13FD143C618E', 'eComWebP', 0, 2);
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (8, 4357, 2855471, 'DE7328C1-2245-4DF6-AA10-3D3BD27E655C', 'eComWebP', 0, 2);
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (11, 4357, 2905974, '0BABEF1B-5A31-4694-BB9F-5A8295D44AB1', 'eComWebP', 0, 2);
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (12, 4357, 2905975, '4CC35907-6906-47B7-853C-87B0DA35CDCC', 'eComWebP', 0, 2);
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (13, 4357, 2905976, '91B8EE50-5F22-4B40-8927-AE67A26FB2A2', 'eComWebP', 0, 2);
INSERT INTO [dbo].[partner_account] ([partner_account_id], [partner_id], [account_id], [partner_account_key], [insert_by], [shared_account], [partner_account_status_id]) VALUES (14, 4357, 2905977, '101CA25E-8E0A-46E1-8132-28D8374F481D', 'eComWebP', 0, 2);
SET IDENTITY_INSERT [dbo].[partner_account] OFF;
 
-- Table: [partner_configuration_partner]
SET IDENTITY_INSERT [dbo].[partner_configuration_partner] ON;
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (2, 4357, 1, 'Standard');
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (5, 2815, 2, 'Yes');
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (6, 2815, 1, 'Standard');
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (13, 1029, 1, 'Standard');
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (14, 1029, 2, 'Yes');
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (16, 4357, 4, 'Required');
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (17, 2815, 4, 'Required');
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (19, 5559, 4, 'Open');
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (20, 8208, 1, 'Quote');
INSERT INTO [dbo].[partner_configuration_partner] ([partner_configuration_partner_id], [partner_id], [partner_configuration_id], [configuration_value]) VALUES (24, 1029, 3, 'Exclude');
SET IDENTITY_INSERT [dbo].[partner_configuration_partner] OFF;
 
-- Table: [product]
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (0, ' Unknown', 1, 7, 0, 0, 0, 0, 0, 0.00, '', '', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2006-08-25 14:35:43.537', 'BOULDER\esmart', 1);
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (1, 'Unknown', 1, 7, 0, 0, 0, 0, 0, 0.00, '', '', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2006-08-25 14:35:43.537', 'BOULDER\esmart', 1);
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (101, 'Webroot T-Shirt', 1, 7, 0, 0, 0, 0, 0, 24.95, 'xxx', 'tshirtxxxx.exe', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2006-08-25 14:35:43.537', 'BOULDER\esmart', 1);
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (102, 'Cache and Cookie Washer - AOL', 1, 7, 0, 0, 0, 0, 0, 0.00, '', '', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2006-08-25 14:35:43.537', 'BOULDER\esmart', 1);
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (103, 'SnapShot - Discontinued', 1, 7, 0, 0, 0, 0, 0, 0.00, '', '', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2006-08-25 14:35:43.537', 'BOULDER\esmart', 1);
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (104, '(1 S/H)', 1, 8, 0, 0, 0, 0, 0, 0.00, '', '', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2006-08-25 14:35:43.537', 'BOULDER\esmart', 1);
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (105, 'Free CD', 1, 7, 0, 0, 0, 0, 0, 0.00, '', '', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2006-08-25 14:35:43.537', 'BOULDER\esmart', 1);
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (110, 'Window Washer CD', 1, 8, 0, 0, 0, 0, 0, 8.95, '', '', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2012-09-23 10:03:34.043', 'WSA2013', 1);
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (111, 'Cache & Cookie Washer CD', 1, 8, 0, 0, 0, 0, 0, 0.00, '', '', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2006-08-25 14:35:43.537', 'BOULDER\esmart', 1);
INSERT INTO [dbo].[product] ([product_id], [product_description], [product_type_id], [product_family_id], [product_lifecycle_id], [license_keycode_type_id], [root_product_id], [uses_keycode], [cd_product_id], [retail_price], [pict], [basename], [insert_date], [insert_by], [modified_date], [modified_by], [online_refund_flag]) VALUES (112, 'Accelerate 2000 CD', 1, 8, 0, 0, 0, 0, 0, 8.95, '', '', '2006-08-25 14:35:43.537', 'BOULDER\esmart', '2006-08-25 14:35:43.537', 'BOULDER\esmart', 1);
 
-- Table: [product_family]
SET IDENTITY_INSERT [dbo].[product_family] ON;
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (1, 'Webroot Secure Anywhere', 'SS', '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (2, 'Webroot Secure Anywhere International', 'SS', '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (3, 'Window Washer', 'WW', '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (4, 'Desktop Firewall', 'FW', '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (5, 'Pop Up Washer', 'PW', '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (6, 'Spam Shredder', 'SP', '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (7, 'Other', NULL, '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (8, 'S/H', NULL, '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (9, 'Spy Sweeper Enterprise', 'SS', '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
INSERT INTO [dbo].[product_family] ([product_family_id], [product_family_description], [product_family_prefix], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (10, 'Window Washer International', 'WW', '2006-08-25 14:30:47.990', 'BOULDER\esmart', '2006-08-25 14:30:47.990', 'BOULDER\esmart');
SET IDENTITY_INSERT [dbo].[product_family] OFF;
 
-- Table: [product_license_category]
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (140, 1, NULL);
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (64012, 1, NULL);
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (64150, 1, NULL);
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (64151, 1, 0);
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (64152, 1, 0);
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (64153, 1, 0);
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (64154, 1, NULL);
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (64159, 1, 0);
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (64160, 1, NULL);
INSERT INTO [dbo].[product_license_category] ([product_id], [license_category_id], [current_license_category_id]) VALUES (64161, 1, 0);
 
-- Table: [product_line]
SET IDENTITY_INSERT [dbo].[product_line] ON;
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (1, 'Webroot Secure Anywhere', 'SS', 64150, '2006-09-12 14:30:50.177', 'BOULDER\esmart', '2006-09-12 14:30:50.177', 'BOULDER\esmart', 0, NULL);
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (2, 'Desktop Firewall', 'FW', 54150, '2006-09-12 14:30:50.177', 'BOULDER\esmart', '2006-09-12 14:30:50.177', 'BOULDER\esmart', 0, NULL);
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (3, 'Window Washer', 'WW', 4060, '2006-09-12 14:30:50.177', 'BOULDER\esmart', '2006-09-12 14:30:50.177', 'BOULDER\esmart', 0, NULL);
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (4, 'Pop Up Washer', 'PW', 42150, '2006-09-12 14:30:50.177', 'BOULDER\esmart', '2006-09-12 14:30:50.177', 'BOULDER\esmart', 0, NULL);
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (5, 'Spam Shredder', 'SP', 57150, '2006-09-12 14:30:50.177', 'BOULDER\esmart', '2006-09-12 14:30:50.177', 'BOULDER\esmart', 0, NULL);
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (6, 'Webroot Secure Anywhere International', 'SS', 64250, '2006-09-12 14:54:54.157', 'BOULDER\esmart', '2006-09-12 14:54:54.157', 'BOULDER\esmart', 0, NULL);
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (7, 'Desktop Firewall International', 'FW', 54250, '2006-09-12 14:55:14.907', 'BOULDER\esmart', '2006-09-12 14:55:14.907', 'BOULDER\esmart', 0, NULL);
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (8, 'Window Washer International', 'WW', 4160, '2006-09-12 14:55:42.300', 'BOULDER\esmart', '2006-09-12 14:55:42.300', 'BOULDER\esmart', 0, NULL);
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (9, 'Pop Up Washer International', 'PW', 42250, '2006-09-12 14:56:06.347', 'BOULDER\esmart', '2006-09-12 14:56:06.347', 'BOULDER\esmart', 0, NULL);
INSERT INTO [dbo].[product_line] ([product_line_id], [product_line_description], [product_line_prefix], [root_product_id], [insert_date], [insert_by], [modified_date], [modified_by], [status], [product_line_cart_type]) VALUES (10, 'Spam Shedder International', 'SP', 57250, '2006-09-12 14:56:58.410', 'BOULDER\esmart', '2006-09-12 14:56:58.410', 'BOULDER\esmart', 0, NULL);
SET IDENTITY_INSERT [dbo].[product_line] OFF;
 
-- Table: [product_line_product]
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (12, 401);
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (3, 4060);
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (3, 4061);
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (3, 4062);
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (3, 4063);
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (3, 4070);
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (3, 4071);
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (3, 4072);
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (3, 4080);
INSERT INTO [dbo].[product_line_product] ([product_line_id], [product_id]) VALUES (3, 4081);
 
-- Table: [product_platform]
SET IDENTITY_INSERT [dbo].[product_platform] ON;
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (1, 'SaaS', 'automated');
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (2, 'Azure EA', 'manual');
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (3, 'On-Prem', 'manual');
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (4, 'HWaaS', NULL);
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (5, 'E2', NULL);
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (6, 'Virtual', NULL);
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (7, 'Physical', NULL);
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (8, 'Windows Virtual Edition per VM', NULL);
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (9, 'Win - Hyper-V Recovery Appliance', NULL);
INSERT INTO [dbo].[product_platform] ([product_platform_id], [product_platform_name], [vault_provisioning]) VALUES (10, 'Win - vSphere Recovery Appliance', NULL);
SET IDENTITY_INSERT [dbo].[product_platform] OFF;
 
-- Table: [product_pricing]
SET IDENTITY_INSERT [dbo].[product_pricing] ON;
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (1, 11100110, 'EN', 'USA', 1, 49.99, '2011-10-03 22:18:56.157', 'BOULDER\mdabbi', NULL, NULL, NULL);
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (2, 11100115, 'EN', 'USA', 1, 49.99, '2011-10-03 22:18:56.157', 'BOULDER\mdabbi', NULL, NULL, NULL);
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (3, 11100118, 'EN', 'USA', 1, 39.99, '2011-10-03 22:18:56.157', 'BOULDER\mdabbi', NULL, NULL, NULL);
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (4, 11100120, 'EN', 'USA', 1, 92.48, '2024-07-09 14:00:55.520', 'boulder\vsingh8', NULL, NULL, NULL);
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (5, 11100130, 'EN', 'USA', 1, 129.97, '2024-07-09 14:00:55.520', 'boulder\vsingh8', NULL, NULL, NULL);
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (6, 11100310, 'EN', 'USA', 1, 59.99, '2011-10-03 22:18:56.157', 'BOULDER\mdabbi', NULL, NULL, NULL);
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (7, 11100315, 'EN', 'USA', 1, 49.99, '2011-10-03 22:18:56.157', 'BOULDER\mdabbi', NULL, NULL, NULL);
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (8, 11100318, 'EN', 'USA', 1, 49.99, '2011-10-03 22:18:56.157', 'BOULDER\mdabbi', NULL, NULL, NULL);
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (9, 11100320, 'EN', 'USA', 1, 110.98, '2024-07-09 14:00:55.520', 'boulder\vsingh8', NULL, NULL, NULL);
INSERT INTO [dbo].[product_pricing] ([product_pricing_id], [product_id], [language_code], [location_code], [currency_id], [retail_price], [last_modified_date], [last_modified_by], [edu_nfp_price], [govt_price], [usage_price]) VALUES (10, 11100330, 'EN', 'USA', 1, 155.97, '2024-07-09 14:00:55.520', 'boulder\vsingh8', NULL, NULL, NULL);
SET IDENTITY_INSERT [dbo].[product_pricing] OFF;
 
-- Table: [product_seat]
SET IDENTITY_INSERT [dbo].[product_seat] ON;
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (1, 72601, 5, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (2, 72602, 5, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (3, 72603, 5, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (4, 72611, 10, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (5, 72612, 10, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (6, 72613, 10, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (7, 72621, 25, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (8, 72622, 25, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (9, 72623, 25, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
INSERT INTO [dbo].[product_seat] ([product_seat_id], [product_id], [seats], [insert_date], [insert_by], [modified_date], [modified_by], [current_seats]) VALUES (10, 72631, 50, '2006-12-07 08:56:30.673', 'BOULDER\esmart', '2006-12-07 08:56:30.673', 'BOULDER\esmart', NULL);
SET IDENTITY_INSERT [dbo].[product_seat] OFF;
 
-- Table: [product_type]
SET IDENTITY_INSERT [dbo].[product_type] ON;
INSERT INTO [dbo].[product_type] ([product_type_id], [product_type_description], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (1, 'New', '2006-08-25 14:32:49.130', 'BOULDER\esmart', '2006-08-25 14:32:49.130', 'BOULDER\esmart');
INSERT INTO [dbo].[product_type] ([product_type_id], [product_type_description], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (2, 'Renewal', '2006-08-25 14:33:01.863', 'BOULDER\esmart', '2006-08-25 14:33:01.863', 'BOULDER\esmart');
INSERT INTO [dbo].[product_type] ([product_type_id], [product_type_description], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (3, 'Upgrade', '2006-08-25 14:33:13.240', 'BOULDER\esmart', '2006-08-25 14:33:13.240', 'BOULDER\esmart');
INSERT INTO [dbo].[product_type] ([product_type_id], [product_type_description], [insert_date], [insert_by], [modified_date], [modified_by]) VALUES (4, 'Module', '2012-04-10 14:12:04.807', 'BOULDER\mshirley', '2012-04-10 14:12:04.807', 'BOULDER\mshirley');
SET IDENTITY_INSERT [dbo].[product_type] OFF;
 
-- Table: [product_years]
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64151, 1, 0, 0);
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64152, 2, 0, 0);
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64153, 3, 0, 0);
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64159, 1.25, 0, 0);
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64161, 1, 0, 0);
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64162, 2, 0, 0);
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64163, 3, 0, 0);
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64169, 1.25, 0, 0);
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64171, 1, 0, 0);
INSERT INTO [dbo].[product_years] ([product_id], [years], [upgrade_months], [upgrade_days]) VALUES (64172, 2, 0, 0);
 
-- Table: [retention_model]
SET IDENTITY_INSERT [dbo].[retention_model] ON;
INSERT INTO [dbo].[retention_model] ([retention_model_id], [retention_model_name], [retention_model_description], [retention_model_type_id], [insert_date], [insert_by]) VALUES (1, '1 Year', 'Keep backups for 1 year', 1, '2022-10-01 08:48:26.133', 'OPENTEXT\jyueh.adm');
INSERT INTO [dbo].[retention_model] ([retention_model_id], [retention_model_name], [retention_model_description], [retention_model_type_id], [insert_date], [insert_by]) VALUES (2, '7 Year', 'Keep backups for 7 years', 1, '2022-10-01 08:48:26.133', 'OPENTEXT\jyueh.adm');
INSERT INTO [dbo].[retention_model] ([retention_model_id], [retention_model_name], [retention_model_description], [retention_model_type_id], [insert_date], [insert_by]) VALUES (3, 'Custom (Term)', 'Custom (Term-based)', 1, '2022-10-01 08:48:26.133', 'OPENTEXT\jyueh.adm');
INSERT INTO [dbo].[retention_model] ([retention_model_id], [retention_model_name], [retention_model_description], [retention_model_type_id], [insert_date], [insert_by]) VALUES (4, 'Custom (Storage)', 'Custom (Storage-based)', 2, '2022-10-01 08:48:26.133', 'OPENTEXT\jyueh.adm');
SET IDENTITY_INSERT [dbo].[retention_model] OFF;
 
-- Table: [usage_pricing_model]
SET IDENTITY_INSERT [dbo].[usage_pricing_model] ON;
INSERT INTO [dbo].[usage_pricing_model] ([usage_pricing_model_id], [usage_pricing_model_name], [usage_pricing_model_description], [usage_pricing_storageGB], [insert_date], [insert_by]) VALUES (1, 'Advanced', 'Advanced - Device/user based', NULL, '2019-09-25 11:33:53.553', 'BOULDER\ugangichetty');
INSERT INTO [dbo].[usage_pricing_model] ([usage_pricing_model_id], [usage_pricing_model_name], [usage_pricing_model_description], [usage_pricing_storageGB], [insert_date], [insert_by]) VALUES (2, 'Capacity', 'Capacity - Storage based', 100, '2019-09-25 11:33:53.553', 'BOULDER\ugangichetty');
INSERT INTO [dbo].[usage_pricing_model] ([usage_pricing_model_id], [usage_pricing_model_name], [usage_pricing_model_description], [usage_pricing_storageGB], [insert_date], [insert_by]) VALUES (3, 'Standard CBEP 100GB', 'Standard - Device/Storage based', 100, '2020-03-30 08:05:53.743', 'BOULDER\esmart');
INSERT INTO [dbo].[usage_pricing_model] ([usage_pricing_model_id], [usage_pricing_model_name], [usage_pricing_model_description], [usage_pricing_storageGB], [insert_date], [insert_by]) VALUES (4, 'Standard CBEP 25GB', 'Standard - Device/Storage based', 25, '2020-08-20 10:07:13.913', 'BOULDER\ugangichetty');
INSERT INTO [dbo].[usage_pricing_model] ([usage_pricing_model_id], [usage_pricing_model_name], [usage_pricing_model_description], [usage_pricing_storageGB], [insert_date], [insert_by]) VALUES (5, 'Standard OTSF 100GB', 'Standard - User/Storage based', 100, '2020-09-01 14:07:24.727', 'BOULDER\jsingh');
INSERT INTO [dbo].[usage_pricing_model] ([usage_pricing_model_id], [usage_pricing_model_name], [usage_pricing_model_description], [usage_pricing_storageGB], [insert_date], [insert_by]) VALUES (6, 'Original 100 GB', 'Original - Storage based', 100, '2020-11-10 14:28:41.413', 'BOULDER\ugangichetty');
INSERT INTO [dbo].[usage_pricing_model] ([usage_pricing_model_id], [usage_pricing_model_name], [usage_pricing_model_description], [usage_pricing_storageGB], [insert_date], [insert_by]) VALUES (7, 'Compressed 100 GB', 'Compressed - Storage based', 100, '2020-11-10 14:28:41.417', 'BOULDER\ugangichetty');
INSERT INTO [dbo].[usage_pricing_model] ([usage_pricing_model_id], [usage_pricing_model_name], [usage_pricing_model_description], [usage_pricing_storageGB], [insert_date], [insert_by]) VALUES (8, 'Original 1 GB', 'Original - Storage based', 1, '2022-09-14 14:10:12.887', 'OPENTEXT\nnaina.adm');
INSERT INTO [dbo].[usage_pricing_model] ([usage_pricing_model_id], [usage_pricing_model_name], [usage_pricing_model_description], [usage_pricing_storageGB], [insert_date], [insert_by]) VALUES (9, 'Compressed 1 GB', 'Compressed - Storage based', 1, '2022-09-14 14:10:59.827', 'OPENTEXT\nnaina.adm');
SET IDENTITY_INSERT [dbo].[usage_pricing_model] OFF;
