apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://github.com/abhishek09exe/ecom-new
    targetRevision: agents/k8s-deployment-sqlserver-prometheus-grafana
    path: deploy/argocd
    directory:
      include: "namespaces.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
