apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/abhishek09exe/ecom-new
    targetRevision: agents/k8s-deployment-sqlserver-prometheus-grafana
    path: deploy/sealed-secrets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
