apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/abhishek09exe/ecom-new
    targetRevision: agents/k8s-deployment-sqlserver-prometheus-grafana
    path: deploy/charts/ui
    helm:
      releaseName: ui-dev
      valueFiles:
        - ../../envs/dev/ui-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecom-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
